basePath: /api/v1
definitions:
  ucenter.UserCreatedResultVO:
    properties:
      uid:
        type: string
    type: object
  ucenter.WebUserCreatedRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - name
    - password
    - phone
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9191
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is berry im server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Berry IM API
  version: "1.0"
paths:
  /ucenter/create:
    post:
      consumes:
      - application/json
      description: 创建用户
      parameters:
      - description: 请求参数
        in: body
        name: webReq
        required: true
        schema:
          $ref: '#/definitions/ucenter.WebUserCreatedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ucenter.UserCreatedResultVO'
      summary: 创建用户
      tags:
      - ucenter
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
